# ~/.config/yazi/keymap.toml
# User needs to provide their desired Yazi keybindings here.
# Example:
# [manager.prepend_keymap]
# on = ["k"]
# run = "move_down"
#
# [manager.prepend_keymap]
# on = ["j"]
# run = "move_up"